-- chaos-mq outbox 表（PostgreSQL 12+）。
create table if not exists chaos_mq_outbox (
    id bigint generated by default as identity primary key,
    message_id varchar(128) not null,
    topic varchar(255) not null,
    tag varchar(128),
    payload_json text not null,
    headers_json text not null,
    status varchar(32) not null,
    retry_times integer not null default 0,
    next_retry_at timestamptz,
    claimed_at timestamptz,
    claim_owner varchar(128),
    last_error varchar(1024),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_chaos_mq_outbox_message_id unique (message_id)
);

create index if not exists idx_chaos_mq_outbox_due
    on chaos_mq_outbox (status, next_retry_at, created_at);

create index if not exists idx_chaos_mq_outbox_claimed
    on chaos_mq_outbox (status, claimed_at);

create index if not exists idx_chaos_mq_outbox_updated
    on chaos_mq_outbox (status, updated_at);
