-- chaos-mq outbox 表（H2）。
create table if not exists chaos_mq_outbox (
    id bigint generated by default as identity primary key,
    message_id varchar(128) not null,
    topic varchar(255) not null,
    tag varchar(128),
    payload_json clob not null,
    headers_json clob not null,
    status varchar(32) not null,
    retry_times int not null default 0,
    next_retry_at timestamp,
    claimed_at timestamp,
    claim_owner varchar(128),
    last_error varchar(1024),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_chaos_mq_outbox_message_id unique (message_id)
);

-- 到期抢占：status in (PENDING, RETRYING) and next_retry_at <= now
create index if not exists idx_chaos_mq_outbox_due
    on chaos_mq_outbox (status, next_retry_at, created_at);

-- 发送超时回收：status = SENDING and claimed_at <= timeout
create index if not exists idx_chaos_mq_outbox_claimed
    on chaos_mq_outbox (status, claimed_at);

-- 已发送清理：status = SENT and updated_at < retention
create index if not exists idx_chaos_mq_outbox_updated
    on chaos_mq_outbox (status, updated_at);
