-- chaos-framework 审计事件表。
-- 该脚本使用较通用的 SQL 语法，适合 H2、PostgreSQL 风格数据库和本地测试；生产 MySQL 可参考 db/mysql/chaos-audit-schema.sql。

CREATE TABLE IF NOT EXISTS chaos_audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(128) NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    principal_id VARCHAR(128) NOT NULL DEFAULT '',
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    client_id VARCHAR(128) NOT NULL DEFAULT '',
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    ip VARCHAR(64) NOT NULL DEFAULT '',
    uri VARCHAR(512) NOT NULL DEFAULT '',
    reason VARCHAR(512) NOT NULL DEFAULT '',
    occurred_at TIMESTAMP NOT NULL,
    attributes TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chaos_audit_event_occurred_at ON chaos_audit_event (occurred_at);
CREATE INDEX IF NOT EXISTS idx_chaos_audit_event_trace_id ON chaos_audit_event (trace_id);
CREATE INDEX IF NOT EXISTS idx_chaos_audit_event_principal_id ON chaos_audit_event (principal_id);
CREATE INDEX IF NOT EXISTS idx_chaos_audit_event_tenant_id ON chaos_audit_event (tenant_id);
CREATE INDEX IF NOT EXISTS idx_chaos_audit_event_action ON chaos_audit_event (action);
