CREATE TABLE IF NOT EXISTS biz_order
(
    id BIGINT PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    buyer_id VARCHAR(64) NOT NULL,
    amount DECIMAL(18, 2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_by VARCHAR(64),
    created_at TIMESTAMP,
    updated_by VARCHAR(64),
    updated_at TIMESTAMP,
    deleted INTEGER DEFAULT 0 NOT NULL
);

-- chaos-mq outbox 表（H2），与 chaos-mq-jdbc 的 db/chaos-mq-outbox-schema-h2.sql 保持一致。
-- 生产环境请使用 chaos-mq-outbox-schema-mysql.sql 或 chaos-mq-outbox-schema-postgresql.sql。
CREATE TABLE IF NOT EXISTS chaos_mq_outbox
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(128) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    tag VARCHAR(128),
    payload_json CLOB NOT NULL,
    headers_json CLOB NOT NULL,
    status VARCHAR(32) NOT NULL,
    retry_times INT DEFAULT 0 NOT NULL,
    next_retry_at TIMESTAMP,
    claimed_at TIMESTAMP,
    claim_owner VARCHAR(128),
    last_error VARCHAR(1024),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_chaos_mq_outbox_message_id UNIQUE (message_id)
);

CREATE INDEX IF NOT EXISTS idx_chaos_mq_outbox_due ON chaos_mq_outbox (status, next_retry_at, created_at);
CREATE INDEX IF NOT EXISTS idx_chaos_mq_outbox_claimed ON chaos_mq_outbox (status, claimed_at);
CREATE INDEX IF NOT EXISTS idx_chaos_mq_outbox_updated ON chaos_mq_outbox (status, updated_at);
