<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.michael</groupId>
        <artifactId>chaos-starters</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>chaos-job-starter</artifactId>
    <name>chaos-job-starter</name>
    <description>Dependency aggregation starter for scheduled job applications.</description>
    <dependencies>
        <dependency>
            <groupId>com.michael</groupId>
            <artifactId>chaos-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.michael</groupId>
            <artifactId>chaos-job</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
